.PHONY: build run-dist setup


clean:
	./gradlew clean

build:
	./gradlew clean build

test:
	./gradlew test

lint:
	./gradlew checkstyleMain


run-dist:
# 	./gradlew installDist
	./build/install/app/bin/app

# setup:
# 	./gradlew clean
