.PHONY: build run-dist setup


clean:
	./gradlew clean

build:
	./gradlew clean build

install:
	./gradlew clean installDist

test:
	./gradlew test

lint:
	./gradlew checkstyleMain


run-dist:

	./build/install/app/bin/app

